/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cornucopiabankqueuesystem;

/**
 *
 * @author admin
 */
public class BillPaymentFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BillPaymentFrame.class.getName());

    /**
     * Creates new form BillPaymentFrame
     */
    public BillPaymentFrame() {
        initComponents();
        QueueDatabase.initialize();
        applyRealTimeValidation();
        setupComboBoxLogic();
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 175, 55), 3));
        setLocationRelativeTo(null);
        
        
        
    }
    
    private void setupComboBoxLogic() {
        cmbCategory.addActionListener(evt -> {
            cmbBiller.removeAllItems();
            String selectedCategory = (String) cmbCategory.getSelectedItem();
            
            if (selectedCategory == null) return;
            
            // Populate billers based on the selected category
            switch (selectedCategory) {
                case "Electric Utility":
                    cmbBiller.addItem("Meralco");
                    cmbBiller.addItem("Davao Light");
                    break;
                case "Water Utility":
                    cmbBiller.addItem("Maynilad");
                    cmbBiller.addItem("Manila Water");
                    break;
                case "Telecoms & Internet":
                    cmbBiller.addItem("Globe Telecom / Globe At Home");
                    cmbBiller.addItem("PLDT / Smart");
                    cmbBiller.addItem("Converge");
                    break;
                case "Government Agency":
                    cmbBiller.addItem("SSS (PRN Payment)");
                    cmbBiller.addItem("Pag-IBIG Fund");
                    cmbBiller.addItem("PhilHealth");
                    break;
                case "Credit Cards & Loans":
                    cmbBiller.addItem("BDO Credit Card");
                    cmbBiller.addItem("Metrobank Card");
                    cmbBiller.addItem("Home Credit");
                    break;
            }
        });

        // Automatically add "+63" if a Telecom biller is selected
        cmbBiller.addActionListener(evt -> {
            String selectedBiller = (String) cmbBiller.getSelectedItem();
            if (selectedBiller != null) {
                if (selectedBiller.contains("Globe") || selectedBiller.contains("Smart")) {
                    txtRefNumber.setText("+63");
                } else {
                    txtRefNumber.setText(""); // Clears it for normal billers
                }
            }
        });
        
        // Trigger it once at startup so it loads the first category correctly
        if (cmbCategory.getItemCount() > 0) {
            cmbCategory.setSelectedIndex(0);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbBiller = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRefNumber = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtAccountName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bills Payment Kiosk");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Supported Billers Include:\n   • Meralco, Maynilad, Manila Water\n   • Globe, PLDT, Smart, Converge\n   • SSS, Pag-IBIG, PhilHealth, BIR\n   • Major Credit Cards & Bank Loans\n\nPlease ensure reference details match your physical statement before submitting.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 300, 170));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Biller Category:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 226, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("4. Select Payment Mode (Cash/Check).");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 250, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("1. Select Biller Category & Merchant.");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        cmbCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electric Utility", "Water Utility", "Telecoms & Internet", "Government Agency", "Credit Cards & Loans" }));
        getContentPane().add(cmbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 280, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("2. Enter exact Account / Reference No.");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("BILL DETAILS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Selected Biller:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 100, 20));

        cmbBiller.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Meralco", "Maynilad", "Globe Telecom / Globe At Home", "PLDT / Smart", "SSS (PRN Payment)", "Pag-IBIG Fund" }));
        getContentPane().add(cmbBiller, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 280, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Account / Reference No.:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("BILL PAYMENT INSTRUCTIONS");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));
        getContentPane().add(txtRefNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 280, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("1. Select Biller Category & Merchant.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Account Holder Name:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("5. Check Priority box if eligible.");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 270, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("3. Enter Account Holder Name & Amount.");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        getContentPane().add(txtAccountName, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 280, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Amount Due (PHP ₱)");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, -1));

        txtAmount.addActionListener(this::txtAmountActionPerformed);
        getContentPane().add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 280, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Payment Mode:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Unified Card" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 280, 30));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(139, 101, 8));
        jCheckBox1.setText("Senior / PWD / Pregnant Priority");
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 310, 20));

        jButton1.setBackground(new java.awt.Color(12, 35, 64));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SUBMIT & PRINT TICKET");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(212, 175, 55), 3));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 400, 40));

        btnBack.setBackground(new java.awt.Color(0, 0, 153));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("BACK");
        btnBack.addActionListener(this::btnBackActionPerformed);
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 580, -1, -1));

        clearbtn.setBackground(new java.awt.Color(220, 38, 38));
        clearbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearbtn.setForeground(new java.awt.Color(255, 255, 255));
        clearbtn.setText("CLEAR");
        clearbtn.addActionListener(this::clearbtnActionPerformed);
        getContentPane().add(clearbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rara\\Documents\\CornucopiaUnion\\src\\main\\java\\Images\\billspayment.png")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 770, 690));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("1. Select Biller Category & Merchant.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        KioskFrame kioskk = new KioskFrame();
        
        kioskk.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
        // TODO add your handling code here:
        
        txtRefNumber.setText("");
        txtAccountName.setText("");
        txtAmount.setText("");
        
       
        if (cmbCategory.getItemCount() > 0) cmbCategory.setSelectedIndex(0);
        if (cmbBiller.getItemCount() > 0) cmbBiller.setSelectedIndex(0);
        if (jComboBox1.getItemCount() > 0) jComboBox1.setSelectedIndex(0);
        
        jCheckBox1.setSelected(false);
    }//GEN-LAST:event_clearbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Object category = cmbCategory.getSelectedItem();
        Object biller = cmbBiller.getSelectedItem();
        String refNumber = txtRefNumber.getText().trim();
        String accountName = txtAccountName.getText().trim();
        String amountText = txtAmount.getText().trim();
        Object paymentMode = jComboBox1.getSelectedItem();

        if (!ValidationUtils.isValidComboSelection(category)) {
            ValidationUtils.showError(this, "Please select a biller category.");
            cmbCategory.requestFocusInWindow();
            return;
        }

        if (!ValidationUtils.isValidComboSelection(biller)) {
            ValidationUtils.showError(this, "Please select a billerrrrrrrrrrrrrrr.");
            cmbBiller.requestFocusInWindow();
            return;
        }

        if (!ValidationUtils.isValidNumericReferenceNumber(refNumber)) {
            ValidationUtils.showError(this,
                    "Please enter a valid account/reference number (4-20 digits, numbers only).");
            txtRefNumber.requestFocusInWindow();
            return;
        }

        if (!ValidationUtils.isValidName(accountName)) {
            ValidationUtils.showError(this,
                    "Please enter a james tayao necosia  holder name (letters only).");
            txtAccountName.requestFocusInWindow();
            return;
        }

        if (!ValidationUtils.isValidAmountFormat(amountText)) {
            ValidationUtils.showError(this,
                    "Please enter a valid amount due (numbers only, e.g. 1500 or 1500.00).");
            txtAmount.requestFocusInWindow();
            return;
        }

        Double amount = ValidationUtils.parseAmount(amountText);
        if (amount == null || amount <= 0) {
            ValidationUtils.showError(this, "Amount due must be greater than zero.");
            txtAmount.requestFocusInWindow();
            return;
        }

        if (!ValidationUtils.isValidComboSelection(paymentMode)) {
            ValidationUtils.showError(this, "Please select a payment mode.");
            jComboBox1.requestFocusInWindow();
            return;
        }
        
        // Temporarily strip the "+" just for the numeric check
        if (!ValidationUtils.isValidNumericReferenceNumber(refNumber.replace("+", ""))) {
            ValidationUtils.showError(this,
                    "Please enter a valid account/reference number (4-20 digits, numbers only).");
            txtRefNumber.requestFocusInWindow();
            return;
        }
        
      // --- NEW POP-UP LOGIC STARTS HERE ---
        String finalRef = refNumber;
        
        if (paymentMode.toString().equals("Unified Card")) {
            javax.swing.JTextField accField = new javax.swing.JTextField();
            
            // Forces exactly 11 digits and numbers only
            accField.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    if (!Character.isDigit(evt.getKeyChar()) || accField.getText().length() >= 11) {
                        evt.consume();
                    }
                }
            });

            int option = javax.swing.JOptionPane.showConfirmDialog(this, 
                new Object[]{"Enter 11-digit Bank Account Number:", accField}, 
                "Card Payment", 
                javax.swing.JOptionPane.OK_CANCEL_OPTION);
                
            if (option != javax.swing.JOptionPane.OK_OPTION) {
                return; // Stops if they click cancel
            }
            
            String accNo = accField.getText();
            if (accNo.length() != 11) {
                ValidationUtils.showError(this, "Account number must be exactly 11 digits.");
                return;
            }
            if (QueueDatabase.getBalanceByNumber(accNo) < 0) {
                ValidationUtils.showError(this, "Account number does not exist in the database!");
                return;
            }
            
            if (!ValidationUtils.isValidBillReference(refNumber)) {
             ValidationUtils.showError(this,
            "Please enter a valid account/reference number (4-10 digits, or +639 followed by 9 digits for mobile numbers).");
             txtRefNumber.requestFocusInWindow();
             return;
             }
            
            
            
            // Combines Biller Ref + Bank Account so it auto-fills on Teller screen
            finalRef = refNumber + " / Bank Acc: " + accNo;
        }
        // --- NEW POP-UP LOGIC ENDS HERE ---

        // --- NEW POP-UP LOGIC ENDS HERE ---
        
        // 1. Generate the ticket and save it to the database! (This defines the 'ticket' variable)
        String ticket = QueueDatabase.addTicket("BP", biller.toString(), accountName, jCheckBox1.isSelected());
        QueueDatabase.saveKioskData(ticket, finalRef, amount.longValue());

        // 2. Show the success message
        ValidationUtils.showSuccess(this,
                "Payment accepted!\n"
                + "Queue ticket: " + ticket + "\n"
                + "Biller: " + biller + "\n"
                + "Reference No.: " + finalRef + "\n"
                + "Amount: PHP " + String.format("%,.2f", amount) + "\n"
                + "Priority: " + (jCheckBox1.isSelected() ? "Yes" : "No"));

        clearbtnActionPerformed(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

  private void applyRealTimeValidation() {
    // Reference number: 4-10 digits, or +639 followed by 9 digits
    txtRefNumber.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            String current = txtRefNumber.getText();
            if (c == '+') {
                if (!current.isEmpty()) evt.consume();   // "+" only as the first character
                return;
            }
            if (!Character.isDigit(c)
                    || current.length() >= ValidationUtils.billReferenceMaxLength(current)) {
                evt.consume();
            }
        }
    });

    // Amount: up to 6 whole digits and up to 2 decimals (bills have centavos)
    txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyTyped(java.awt.event.KeyEvent evt) {
            char c = evt.getKeyChar();
            String t = txtAmount.getText();
            int dot = t.indexOf('.');
            if (c == '.') {
                if (dot >= 0 || t.isEmpty()) evt.consume();      // one dot, not first
            } else if (Character.isDigit(c)) {
                if (dot >= 0) {
                    if (t.length() - dot > 2) evt.consume();     // max 2 decimals
                } else if (t.length() >= 6) {
                    evt.consume();                               // max 6 whole digits
                }
            } else {
                evt.consume();
            }
        }
    });
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BillPaymentFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton clearbtn;
    private javax.swing.JComboBox<String> cmbBiller;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField txtAccountName;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtRefNumber;
    // End of variables declaration//GEN-END:variables
}
