/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cornucopiabankqueuesystem;
import javax.swing.*;
import javax.swing.border.LineBorder;
import java.awt.*;
/**
 *
 * @author admin
 */
public class KioskFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KioskFrame.class.getName());
    
    /**
     * Creates new form KioskFrame
     */
    public KioskFrame() {
        initComponents();
       
        setLocationRelativeTo(null);
    }
    
   
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBillsPayment = new javax.swing.JButton();
        btnForeignExchange = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        withdrawbtn = new javax.swing.JButton();
        depositbtn = new javax.swing.JButton();
        fundTransferbtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cornucopia Union - Self-Service Kiosk");
        setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(12, 35, 64));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(251, 191, 36));
        jLabel1.setText("Centria Unified");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 12, -1, 35));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Self-Service Banking Kiosk");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("\"Serving You with Abundance\"");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 752, 100));

        btnBillsPayment.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBillsPayment.setText(" Bills Payment");
        btnBillsPayment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0), 3));
        btnBillsPayment.addActionListener(this::btnBillsPaymentActionPerformed);
        getContentPane().add(btnBillsPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 272, 167, 97));

        btnForeignExchange.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnForeignExchange.setText("Foreign Exchange");
        btnForeignExchange.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0), 3));
        btnForeignExchange.addActionListener(this::btnForeignExchangeActionPerformed);
        getContentPane().add(btnForeignExchange, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 169, 167, 97));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("Account Application");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0), 3));
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 169, 167, 97));

        jPanel1.setBackground(new java.awt.Color(12, 35, 74));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Touch screen to begin • Centria Unified © 2026");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 76, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 516, 752, 139));

        withdrawbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        withdrawbtn.setText("Withdraw");
        withdrawbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0), 3));
        withdrawbtn.addActionListener(this::withdrawbtnActionPerformed);
        getContentPane().add(withdrawbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 381, 167, 97));

        depositbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        depositbtn.setText("Deposit");
        depositbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0), 3));
        depositbtn.addActionListener(this::depositbtnActionPerformed);
        getContentPane().add(depositbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 381, 167, 97));

        fundTransferbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fundTransferbtn.setText("Fund transfer");
        fundTransferbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 215, 0), 3));
        fundTransferbtn.addActionListener(this::fundTransferbtnActionPerformed);
        getContentPane().add(fundTransferbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(579, 272, 167, 97));

        jPanel3.setBackground(new java.awt.Color(244, 246, 249));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(30, 58, 138));
        jLabel4.setText("Welcome! Please select your transaction:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel4)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addContainerGap(413, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 760, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ApplicationFrame APLIframe = new ApplicationFrame();
        
        
        APLIframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnBillsPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillsPaymentActionPerformed
        // TODO add your handling code here:
        BillPaymentFrame billframe = new BillPaymentFrame();
        
        billframe.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnBillsPaymentActionPerformed

    private void withdrawbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawbtnActionPerformed
        // TODO add your handling code here:
        WithdrawKiosk withdrawFrmae = new WithdrawKiosk();
        
        withdrawFrmae.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_withdrawbtnActionPerformed

    private void depositbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositbtnActionPerformed
DepositFrame DepositFrame = new DepositFrame();
        
        DepositFrame.setVisible(true);
        
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_depositbtnActionPerformed

    private void fundTransferbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fundTransferbtnActionPerformed
TransferFunds TransferFunds = new TransferFunds();
        
        TransferFunds.setVisible(true);
        
        this.dispose();             // TODO add your handling code here:
    }//GEN-LAST:event_fundTransferbtnActionPerformed

    private void btnForeignExchangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnForeignExchangeActionPerformed
        // TODO add your handling code here:
        fexchangeFrame fFrame = new fexchangeFrame();
        
        fFrame.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnForeignExchangeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        System.out.println(",eh");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KioskFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBillsPayment;
    private javax.swing.JButton btnForeignExchange;
    private javax.swing.JButton depositbtn;
    private javax.swing.JButton fundTransferbtn;
    private javax.swing.JButton jButton3;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton withdrawbtn;
    // End of variables declaration//GEN-END:variables
}
