/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cornucopiabankqueuesystem;

/**
 *
 * @author James
 */
public class TransferFunds extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TransferFunds.class.getName());

    /**
     * Creates new form TransferFunds
     */
    public TransferFunds() {
        initComponents();
         QueueDatabase.initialize();
         applyRealTimeValidation();
          makeTransparent();   
         setLocationRelativeTo(null);
         jCheckBox1.setIcon(makeBoxIcon(28, false));
         jCheckBox1.setSelectedIcon(makeBoxIcon(28, true));
         jCheckBox1.setOpaque(false);
         jCheckBox1.setContentAreaFilled(false); // helps under Nimbus
    }
    
    private javax.swing.Icon makeBoxIcon(int size, boolean checked) {
    java.awt.image.BufferedImage img =
        new java.awt.image.BufferedImage(size, size, java.awt.image.BufferedImage.TYPE_INT_ARGB);
    java.awt.Graphics2D g = img.createGraphics();
    g.setRenderingHint(java.awt.RenderingHints.KEY_ANTIALIASING,
                       java.awt.RenderingHints.VALUE_ANTIALIAS_ON);
    g.setColor(java.awt.Color.WHITE);
    g.fillRect(1, 1, size - 2, size - 2);
    g.setColor(new java.awt.Color(0, 0, 153));
    g.setStroke(new java.awt.BasicStroke(2));
    g.drawRect(1, 1, size - 3, size - 3);
    if (checked) {
        g.drawLine(size / 5, size / 2, size / 2 - 1, size - size / 4);
        g.drawLine(size / 2 - 1, size - size / 4, size - size / 5, size / 5);
    }
    g.dispose();
    return new javax.swing.ImageIcon(img);
}
    
    
    private void makeTransparent() {
    // Text fields
    javax.swing.JTextField[] fields = {jTextField1, jTextField2, jTextField3, jTextField4};
    for (javax.swing.JTextField tf : fields) {
        tf.setOpaque(false);
        tf.setBackground(new java.awt.Color(0, 0, 0, 0)); // needed for Nimbus
        tf.setBorder(null);
        tf.setForeground(java.awt.Color.BLACK);           // pick a color that shows on your image
    }

    // Buttons
    javax.swing.JButton[] buttons = {jButton4, jButton5, jButton6, jButton7};
    for (javax.swing.JButton b : buttons) {
        b.setOpaque(false);
        b.setContentAreaFilled(false);
        b.setBorderPainted(false);
        b.setFocusPainted(false);
        b.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 153), 2, true));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 30, -1, -1));

        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jPanel3.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 336, 140, 20));

        jTextField2.addActionListener(this::jTextField2ActionPerformed);
        jPanel3.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 140, 20));

        jTextField3.addActionListener(this::jTextField3ActionPerformed);
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 222, 140, 20));
        jPanel3.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 278, 140, 20));

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCheckBox1.setBorder(null);
        jCheckBox1.setIconTextGap(1);
        jCheckBox1.setMaximumSize(new java.awt.Dimension(52, 50));
        jCheckBox1.setMinimumSize(new java.awt.Dimension(50, 50));
        jCheckBox1.setPreferredSize(new java.awt.Dimension(50, 50));
        jCheckBox1.addActionListener(this::jCheckBox1ActionPerformed);
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, -1, -1));

        jButton4.setBackground(new java.awt.Color(12, 35, 74));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.addActionListener(this::jButton4ActionPerformed);
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 100, 30));

        jButton5.setBackground(new java.awt.Color(153, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 130, 36));

        jButton6.setBackground(new java.awt.Color(0, 0, 153));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.addActionListener(this::jButton6ActionPerformed);
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 110, 30));

        jButton7.setBackground(new java.awt.Color(51, 51, 255));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.addActionListener(this::jButton7ActionPerformed);
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Rara\\Documents\\CornucopiaUnion\\src\\main\\java\\Images\\transfund1 (1).png")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 600));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         
        // 1. Read all text fields
        String accountNumber = jTextField2.getText().trim();       // Source Account
        String destinationAccount = jTextField3.getText().trim();  // Destination Account
        String accountName = jTextField4.getText().trim();         // Account Name
        String amountText = jTextField1.getText().trim();          // Transfer Amo);  // Destination Account

        // 2. Validate Source Account
        if (!ValidationUtils.isValidAccountNumber(accountNumber)) {
            ValidationUtils.showError(this,
                    "Please enter a valid source account number (6-20 digits only).");
            jTextField1.requestFocusInWindow();
            return;
        }

        // 3. Validate Destination Account
        if (!ValidationUtils.isValidAccountNumber(destinationAccount)) {
            ValidationUtils.showError(this,
                    "Please enter a valid destination account number (6-20 digits only).");
            jTextField4.requestFocusInWindow();
            return;
        }

        // 4. Ensure Source and Destination are not the same
        if (accountNumber.equals(destinationAccount)) {
            ValidationUtils.showError(this,
                    "Source and destination accounts cannot be the same.");
            jTextField4.requestFocusInWindow();
            return;
        }

        // 5. Validate Amount
        if (!ValidationUtils.isValidWholeAmountFormat(amountText)) {
            ValidationUtils.showError(this,
                    "Please enter the transfer amount in whole pesos only (no centavos).");
            jTextField2.requestFocusInWindow();
            return;
        }
        
        // 6. Validate Account Name
        if (!ValidationUtils.isValidName(accountName)) {
            ValidationUtils.showError(this,
                    "Please enter a valid account name (letters only).");
            jTextField3.requestFocusInWindow();
            return;
        }
        
        // 1. Validate Source Account
        double sourceBalance = QueueDatabase.getBalanceByNumber(accountNumber);
        if (sourceBalance == -2.0) {
            ValidationUtils.showError(this, "Transfer Failed: Your Source Account is LOCKED and cannot be used.");
            return;
        } else if (sourceBalance < 0) {
            ValidationUtils.showError(this, "Transfer Failed: Source Account Number does not exist in our records.");
            return;
        }
        
        if (sourceBalance < Long.parseLong(amountText)) {
            ValidationUtils.showError(this, "Transfer Failed: Insufficient funds in the Source Account.");
            return;
        }

        // 2. Validate Destination Account
        double destBalance = QueueDatabase.getAccountBalance(destinationAccount, accountName);
        if (destBalance == -2.0) {
            ValidationUtils.showError(this, "Transfer Failed: The Destination Account is LOCKED and cannot receive funds.");
            return;
        } else if (destBalance < 0) {
            ValidationUtils.showError(this, "Transfer Failed: Destination Account Number and Name do not match our records.");
            return;
        }

        long amount = Long.parseLong(amountText);
        if (amount < 1) { 
            ValidationUtils.showError(this, "Minimum transfer amount is PHP 1.");
            jTextField2.requestFocusInWindow();
            return;
        }
        if (amount > 500000) { 
            ValidationUtils.showError(this, "Maximum digital transfer per transaction is PHP 500,000.");
            jTextField2.requestFocusInWindow();
            return;
        }

        // 6. Validate Account Name
        if (!ValidationUtils.isValidName(accountName)) {
            ValidationUtils.showError(this,
                    "Please enter a valid account name (letters only).");
            jTextField3.requestFocusInWindow();
            return;
        }
        
        

        // 7. Generate the "TR" ticket for Transfer
        String ticket = QueueDatabase.addTicket("TR", "Transfer Funds", accountName, jCheckBox1.isSelected());
        
        // 8. Save all data using the new 4-parameter method you added to QueueDatabase
        QueueDatabase.saveKioskData(ticket, accountNumber, destinationAccount, amount);

        // 9. Show Success Prompt
        ValidationUtils.showSuccess(this,
                "Transfer request submitted!\n"
                + "Queue ticket: " + ticket + "\n"
                + "Source: " + accountNumber + "\n"
                + "Destination: " + destinationAccount + "\n"
                + "Amount: PHP " + String.format("%,d", amount) + "\n"
                + "Priority: " + (jCheckBox1.isSelected() ? "Yes" : "No"));

        // 10. Call your reset or back button to clear the fields
        jButton5ActionPerformed(evt); 
    
        
        
    }//GEN-LAST:event_jButton4ActionPerformed
     
    private void applyRealTimeValidation() {
        // Source Account: Max 11 digits, numbers only
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (!Character.isDigit(evt.getKeyChar()) || jTextField2.getText().length() >= 11) evt.consume();
            }
        });

        // Destination Account: Max 11 digits, numbers only
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (!Character.isDigit(evt.getKeyChar()) || jTextField3.getText().length() >= 11) evt.consume();
            }
        });

        // Transfer Amount: Max 6 digits, whole numbers only (no decimals)
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                if (!Character.isDigit(evt.getKeyChar()) || jTextField1.getText().length() >= 6) evt.consume();
            }
        });
    }
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jLabel14.setText("");
        jCheckBox1.setSelected(false);
        jTextField2.requestFocusInWindow();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        KioskFrame kioskF = new KioskFrame();
        kioskF.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    String accNo = jTextField2.getText().trim();

    if (!accNo.matches("\\d{11}")) {
        jLabel14.setText("");
        ValidationUtils.showError(this, "Enter your 11-digit source account number first.");
        jTextField2.requestFocusInWindow();
        return;
    }

    String[] details = QueueDatabase.getAccountDetails(accNo);

    if (details == null) {
        jLabel14.setText("");
        ValidationUtils.showError(this, "Source account number does not exist in our records.");
    } else if ("LOCKED".equals(details[4])) {
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel14.setForeground(java.awt.Color.RED);
        jLabel14.setText("Account is LOCKED");
    } else {
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jLabel14.setForeground(new java.awt.Color(0, 100, 0));
        jLabel14.setText("Balance: PHP " + String.format("%,.2f", Double.parseDouble(details[3])));
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TransferFunds().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
